{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Values.application.name }}
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        maxAllowed:
          {{- toYaml .Values.vpa.maxAllowed | nindent 10 }}
        minAllowed:
          {{- toYaml .Values.vpa.minAllowed | nindent 10 }}
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.application.name }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode }}
{{- end}}
